# Generated by Django 4.2 on 2023-05-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&psig=AOvVaw0dRLg5BmLQQiebCe9bGF_M&ust=1683084535767000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIiS8dDY1f4CFQAAAAAdAAAAABAD', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(),
        ),
    ]
